# PS1="\[\033[01;33m\]\w\[\033[00m\]\$ "
PS1="[\u:\h \[\033[01;33m\]\w\[\033[00m\]]$ "
export EDITOR="vim"
export ARCHFLAGS="-arch x86_64"

# alias lc="ls -GF"
alias ls="ls -G"
alias ll="ls -l"

PATH="/usr/local/ruby/bin:$PATH"
PATH="/usr/local/mysql/bin:/usr/local/python/bin:/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH"
# Append gcc path temporarily
# PATH="/Applications/Xcode.app/Contents/Developer/usr/bin:$PATH"

export PATH


